#!/usr/bin/env python3
"""synth.py: generate synthetic programs into synth/ that stress the Map#Glue/IMap#Glue element axioms.

Each family scales one use of a comprehension's elements with a size N:
  chain   - lookup through N nested comprehensions (each over the previous one's domain)
  lookups - N lookups into one comprehension
  spec    - N calls of a method whose postcondition is a comprehension over old(M), then a
            lookup; the shape of dafny4/UnionFind.dfy's Main
  equal   - N extensional equalities between comprehensions
  keyed   - N lookups into a comprehension with a key expression (x + 1 := ...)
  update  - N updates of a comprehension, then lookups through the updates
  ichain, ilookups - chain and lookups with imap
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "synth")
SIZES = [1, 2, 4, 8, 16]


def chain(n, kind="map"):
    lines = [f"method Chain(m0: {kind}<int, int>, k: int)", "  requires k in m0", "{"]
    for i in range(1, n + 1):
        lines.append(f"  var m{i} := {kind} x | x in m{i-1} :: m{i-1}[x] + 1;")
    lines += [f"  assert m{n}[k] == m0[k] + {n};", "}"]
    return "\n".join(lines)


def lookups(n, kind="map"):
    ks = [f"k{i}" for i in range(n)]
    lines = [f"method Lookups(m0: {kind}<int, int>, {', '.join(k + ': int' for k in ks)})",
             "  requires " + " && ".join(f"{k} in m0" for k in ks), "{",
             f"  var m := {kind} x | x in m0 :: 2 * m0[x];",
             f"  assert {' + '.join(f'm[{k}]' for k in ks)} == 2 * ({' + '.join(f'm0[{k}]' for k in ks)});",
             "}"]
    return "\n".join(lines)


def spec(n):
    calls = "\n".join(f"  s.Bump({i});" for i in range(n))
    return f"""class Store {{
  var M: map<int, int>
  method Bump(r: int)
    modifies this
    ensures M == map x | x in old(M) :: if old(M)[x] == r then r + 1 else old(M)[x]
  {{
    M := map x | x in M :: if M[x] == r then r + 1 else M[x];
  }}
}}

method Spec(s: Store, k: int)
  modifies s
  requires k in s.M && s.M[k] == 0
{{
{calls}
  assert s.M[k] == {n};
}}"""


def equal(n):
    body = "\n".join(f"  assert (map x | x in s :: x + {i}) == (map x | x in s :: {i} + x);" for i in range(n))
    return f"method Equal(s: set<int>)\n{{\n{body}\n}}"


def keyed(n):
    ks = [f"k{i}" for i in range(n)]
    lines = [f"method Keyed(s: set<int>, {', '.join(k + ': int' for k in ks)})",
             "  requires " + " && ".join(f"{k} in s" for k in ks), "{",
             "  var m := map x | x in s :: x + 1 := 2 * x;",
             f"  assert {' + '.join(f'm[{k} + 1]' for k in ks)} == 2 * ({' + '.join(ks)});",
             "}"]
    return "\n".join(lines)


def update(n):
    lines = ["method Update(s: set<int>, k: int)", "  requires k in s && k > 0", "{",
             "  var m := map x | x in s :: 2 * x;"]
    for i in range(n):
        lines.append(f"  m := m[-{i + 1} := {i}];")
    lines += ["  assert m[k] == 2 * k;", "}"]
    return "\n".join(lines)


FAMILIES = {"chain": chain, "lookups": lookups, "spec": spec, "equal": equal, "keyed": keyed,
            "update": update, "ichain": lambda n: chain(n, "imap"),
            "ilookups": lambda n: lookups(n, "imap")}

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for name, f in FAMILIES.items():
        for n in SIZES:
            with open(os.path.join(OUT, f"{name}-{n:02d}.dfy"), "w") as fh:
                fh.write(f"// Generated by gen_synth.py: family {name}, N = {n}\n\n{f(n)}\n")
    print(len(os.listdir(OUT)), "programs in", OUT)
